from __future__ import annotations

from enum import Enum


class Event(str, Enum):
    USER_TEXT = "USER_TEXT"
    RISK_ALERT = "RISK_ALERT"
    RISK_HANDOFF_STARTED = "RISK_HANDOFF_STARTED"
    RISK_HANDOFF_ACKED = "RISK_HANDOFF_ACKED"
    RESUME_AFTER_RISK = "RESUME_AFTER_RISK"
    MISSING_FIELD = "MISSING_FIELD"
    SCHEMA_VIOLATION = "SCHEMA_VIOLATION"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    PHASE_DONE = "PHASE_DONE"
    MODULE_DONE = "MODULE_DONE"
    EXPORT_REPORT = "EXPORT_REPORT"
    COMORBIDITY_EXPLORE = "COMORBIDITY_EXPLORE"
    PHASE_ENTER = "PHASE_ENTER"
    PHASE_LEAVE = "PHASE_LEAVE"
